{
 "title": "Servo",
 "time": { "from": "2025-04-15T15:49:05.144Z", "to": "2025-04-15T16:00:24.513Z" },
 "panels": [
  { "title": "Ambiant", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Air",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n    -- Temperature Data for SensorA\n    CASE \n        WHEN CAST(t.SensorAir AS FLOAT) = -1 THEN NULL \n        ELSE CAST(t.SensorAir AS FLOAT) \n    END AS Temp,\n    -- Humidity Data for SensorA\n    CASE \n        WHEN CAST(h.SensorAir AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorAir AS INTEGER) \n    END AS Hum\nFROM \n    (SELECT * FROM TemperatureData ORDER BY id DESC LIMIT 1) t\nCROSS JOIN \n    (SELECT * FROM HumidityData ORDER BY id DESC LIMIT 1) h;\n",
     "rawQueryText": "SELECT \n    -- Temperature Data for SensorA\n    CASE \n        WHEN CAST(t.SensorAir AS FLOAT) = -1 THEN NULL \n        ELSE CAST(t.SensorAir AS FLOAT) \n    END AS Temp,\n    -- Humidity Data for SensorA\n    CASE \n        WHEN CAST(h.SensorAir AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorAir AS INTEGER) \n    END AS Hum\nFROM \n    (SELECT * FROM TemperatureData ORDER BY id DESC LIMIT 1) t\nCROSS JOIN \n    (SELECT * FROM HumidityData ORDER BY id DESC LIMIT 1) h;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Température",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "queryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorAir AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorAir AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "rawQueryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorAir AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorAir AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Humidité",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "queryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorAir AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorAir AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "rawQueryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorAir AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorAir AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Capteurs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Capteur 0",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n    -- Temperature Data for SensorA\n    CASE \n        WHEN CAST(t.SensorA AS FLOAT) = -1 THEN NULL \n        ELSE CAST(t.SensorA AS FLOAT) \n    END AS Temp,\n    -- Humidity Data for SensorA\n    CASE \n        WHEN CAST(h.SensorA AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorA AS INTEGER) \n    END AS Hum\nFROM \n    (SELECT * FROM TemperatureData ORDER BY id DESC LIMIT 1) t\nCROSS JOIN \n    (SELECT * FROM HumidityData ORDER BY id DESC LIMIT 1) h;\n",
     "rawQueryText": "SELECT \n    -- Temperature Data for SensorA\n    CASE \n        WHEN CAST(t.SensorA AS FLOAT) = -1 THEN NULL \n        ELSE CAST(t.SensorA AS FLOAT) \n    END AS Temp,\n    -- Humidity Data for SensorA\n    CASE \n        WHEN CAST(h.SensorA AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorA AS INTEGER) \n    END AS Hum\nFROM \n    (SELECT * FROM TemperatureData ORDER BY id DESC LIMIT 1) t\nCROSS JOIN \n    (SELECT * FROM HumidityData ORDER BY id DESC LIMIT 1) h;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Température",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 14 },
   "targets": [
    {
     "queryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorA AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorA AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "rawQueryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorA AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorA AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Capteur 1",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorB AS FLOAT) = -1 THEN NULL \n        ELSE CAST(t.SensorB AS FLOAT) \n    END AS Temp,\n    -- Humidity Data\n    CASE \n        WHEN CAST(h.SensorB AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorB AS INTEGER) \n    END AS Hum\nFROM \n    (SELECT * FROM TemperatureData ORDER BY id DESC LIMIT 1) t\nCROSS JOIN \n    (SELECT * FROM HumidityData ORDER BY id DESC LIMIT 1) h;\n",
     "rawQueryText": "SELECT \n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorB AS FLOAT) = -1 THEN NULL \n        ELSE CAST(t.SensorB AS FLOAT) \n    END AS Temp,\n    -- Humidity Data\n    CASE \n        WHEN CAST(h.SensorB AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorB AS INTEGER) \n    END AS Hum\nFROM \n    (SELECT * FROM TemperatureData ORDER BY id DESC LIMIT 1) t\nCROSS JOIN \n    (SELECT * FROM HumidityData ORDER BY id DESC LIMIT 1) h;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Température",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "queryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorB AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorB AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "rawQueryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorB AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorB AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Humidité",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 19 },
   "targets": [
    {
     "queryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorA AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorA AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "rawQueryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorA AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorA AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Humidité",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 19 },
   "targets": [
    {
     "queryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorB AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorB AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "rawQueryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorB AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorB AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Capteur 2",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n    -- Temperature Data for SensorC\n    CASE \n        WHEN CAST(t.SensorC AS FLOAT) = -1 THEN NULL \n        ELSE CAST(t.SensorC AS FLOAT) \n    END AS Temp,\n    -- Humidity Data for SensorC\n    CASE \n        WHEN CAST(h.SensorC AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorC AS INTEGER) \n    END AS Hum\nFROM \n    (SELECT * FROM TemperatureData ORDER BY id DESC LIMIT 1) t\nCROSS JOIN \n    (SELECT * FROM HumidityData ORDER BY id DESC LIMIT 1) h;\n",
     "rawQueryText": "SELECT \n    -- Temperature Data for SensorC\n    CASE \n        WHEN CAST(t.SensorC AS FLOAT) = -1 THEN NULL \n        ELSE CAST(t.SensorC AS FLOAT) \n    END AS Temp,\n    -- Humidity Data for SensorC\n    CASE \n        WHEN CAST(h.SensorC AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorC AS INTEGER) \n    END AS Hum\nFROM \n    (SELECT * FROM TemperatureData ORDER BY id DESC LIMIT 1) t\nCROSS JOIN \n    (SELECT * FROM HumidityData ORDER BY id DESC LIMIT 1) h;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Température",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 24 },
   "targets": [
    {
     "queryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorC AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorC AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "rawQueryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorC AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorC AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Capteur 3",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n    -- Temperature Data for SensorC\n    CASE \n        WHEN CAST(t.SensorD AS FLOAT) = -1 THEN NULL \n        ELSE CAST(t.SensorD AS FLOAT) \n    END AS Temp,\n    -- Humidity Data for SensorC\n    CASE \n        WHEN CAST(h.SensorD AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorD AS INTEGER) \n    END AS Hum\nFROM \n    (SELECT * FROM TemperatureData ORDER BY id DESC LIMIT 1) t\nCROSS JOIN \n    (SELECT * FROM HumidityData ORDER BY id DESC LIMIT 1) h;\n",
     "rawQueryText": "SELECT \n    -- Temperature Data for SensorC\n    CASE \n        WHEN CAST(t.SensorD AS FLOAT) = -1 THEN NULL \n        ELSE CAST(t.SensorD AS FLOAT) \n    END AS Temp,\n    -- Humidity Data for SensorC\n    CASE \n        WHEN CAST(h.SensorD AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorD AS INTEGER) \n    END AS Hum\nFROM \n    (SELECT * FROM TemperatureData ORDER BY id DESC LIMIT 1) t\nCROSS JOIN \n    (SELECT * FROM HumidityData ORDER BY id DESC LIMIT 1) h;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Température",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 24 },
   "targets": [
    {
     "queryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorD AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorD AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "rawQueryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorD AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorD AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Humidité",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 29 },
   "targets": [
    {
     "queryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorC AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorC AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "rawQueryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorC AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorC AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Humidité",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 29 },
   "targets": [
    {
     "queryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorD AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorD AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "rawQueryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorD AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorD AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Mux 1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mux 1",
     "type": "gauge",
     "gridPos": { "h": 20, "w": 6, "x": 0, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT \n    -- Temperature Data\n    CASE WHEN CAST(t.SensorA_1 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorA_1 AS FLOAT) END AS \"Temp 1\",\n    CASE WHEN CAST(h.SensorA_1 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorA_1 AS INTEGER) END AS \"Hum 1\",\n    CASE WHEN CAST(t.SensorA_2 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorA_2 AS FLOAT) END AS \"Temp 2\",\n    CASE WHEN CAST(h.SensorA_2 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorA_2 AS INTEGER) END AS \"Hum 2\",\n    CASE WHEN CAST(t.SensorA_3 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorA_3 AS FLOAT) END AS \"Temp 3\",\n    CASE WHEN CAST(h.SensorA_3 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorA_3 AS INTEGER) END AS \"Hum 3\",\n    CASE WHEN CAST(t.SensorA_4 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorA_4 AS FLOAT) END AS \"Temp 4\",\n    CASE WHEN CAST(h.SensorA_4 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorA_4 AS INTEGER) END AS \"Hum 4\"\nFROM \n    (SELECT * FROM TemperatureData ORDER BY id DESC LIMIT 1) t\nCROSS JOIN \n    (SELECT * FROM HumidityData ORDER BY id DESC LIMIT 1) h;\n",
       "rawQueryText": "SELECT \n    -- Temperature Data\n    CASE WHEN CAST(t.SensorA_1 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorA_1 AS FLOAT) END AS \"Temp 1\",\n    CASE WHEN CAST(h.SensorA_1 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorA_1 AS INTEGER) END AS \"Hum 1\",\n    CASE WHEN CAST(t.SensorA_2 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorA_2 AS FLOAT) END AS \"Temp 2\",\n    CASE WHEN CAST(h.SensorA_2 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorA_2 AS INTEGER) END AS \"Hum 2\",\n    CASE WHEN CAST(t.SensorA_3 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorA_3 AS FLOAT) END AS \"Temp 3\",\n    CASE WHEN CAST(h.SensorA_3 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorA_3 AS INTEGER) END AS \"Hum 3\",\n    CASE WHEN CAST(t.SensorA_4 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorA_4 AS FLOAT) END AS \"Temp 4\",\n    CASE WHEN CAST(h.SensorA_4 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorA_4 AS INTEGER) END AS \"Hum 4\"\nFROM \n    (SELECT * FROM TemperatureData ORDER BY id DESC LIMIT 1) t\nCROSS JOIN \n    (SELECT * FROM HumidityData ORDER BY id DESC LIMIT 1) h;\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Température 1",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 6, "y": 35 },
     "targets": [
      {
       "queryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorA_1 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorA_1 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorA_1 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorA_1 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Humidité 1",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 35 },
     "targets": [
      {
       "queryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorA_1 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorA_1 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorA_1 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorA_1 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Température 2",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 6, "y": 80 },
     "targets": [
      {
       "queryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorA_2 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorA_2 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorA_2 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorA_2 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Humidité 2",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 80 },
     "targets": [
      {
       "queryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorA_2 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorA_2 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorA_2 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorA_2 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Température 3",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 6, "y": 85 },
     "targets": [
      {
       "queryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorA_3 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorA_3 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorA_3 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorA_3 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Humidité 3",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 85 },
     "targets": [
      {
       "queryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorA_3 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorA_3 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorA_3 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorA_3 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Température",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 6, "y": 90 },
     "targets": [
      {
       "queryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorA_4 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorA_4 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorA_4 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorA_4 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Humidité 4",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 90 },
     "targets": [
      {
       "queryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorA_4 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorA_4 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorA_4 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorA_4 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  { "title": "Mux 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Mux 2",
   "type": "gauge",
   "gridPos": { "h": 20, "w": 6, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n    -- Temperature Data\n    CASE WHEN CAST(t.SensorB_1 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorB_1 AS FLOAT) END AS \"Temp 1\",\n    CASE WHEN CAST(h.SensorB_1 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorB_1 AS INTEGER) END AS \"Hum 1\",\n    CASE WHEN CAST(t.SensorB_2 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorB_2 AS FLOAT) END AS \"Temp 2\",\n    CASE WHEN CAST(h.SensorB_2 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorB_2 AS INTEGER) END AS \"Hum 2\",\n    CASE WHEN CAST(t.SensorB_3 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorB_3 AS FLOAT) END AS \"Temp 3\",\n    CASE WHEN CAST(h.SensorB_3 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorB_3 AS INTEGER) END AS \"Hum 3\",\n    CASE WHEN CAST(t.SensorB_4 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorB_4 AS FLOAT) END AS \"Temp 4\",\n    CASE WHEN CAST(h.SensorB_4 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorB_4 AS INTEGER) END AS \"Hum 4\"\nFROM \n    (SELECT * FROM TemperatureData ORDER BY id DESC LIMIT 1) t\nCROSS JOIN \n    (SELECT * FROM HumidityData ORDER BY id DESC LIMIT 1) h;\n",
     "rawQueryText": "SELECT \n    -- Temperature Data\n    CASE WHEN CAST(t.SensorB_1 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorB_1 AS FLOAT) END AS \"Temp 1\",\n    CASE WHEN CAST(h.SensorB_1 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorB_1 AS INTEGER) END AS \"Hum 1\",\n    CASE WHEN CAST(t.SensorB_2 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorB_2 AS FLOAT) END AS \"Temp 2\",\n    CASE WHEN CAST(h.SensorB_2 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorB_2 AS INTEGER) END AS \"Hum 2\",\n    CASE WHEN CAST(t.SensorB_3 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorB_3 AS FLOAT) END AS \"Temp 3\",\n    CASE WHEN CAST(h.SensorB_3 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorB_3 AS INTEGER) END AS \"Hum 3\",\n    CASE WHEN CAST(t.SensorB_4 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorB_4 AS FLOAT) END AS \"Temp 4\",\n    CASE WHEN CAST(h.SensorB_4 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorB_4 AS INTEGER) END AS \"Hum 4\"\nFROM \n    (SELECT * FROM TemperatureData ORDER BY id DESC LIMIT 1) t\nCROSS JOIN \n    (SELECT * FROM HumidityData ORDER BY id DESC LIMIT 1) h;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Température 1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 36 },
   "targets": [
    {
     "queryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorB_1 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorB_1 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "rawQueryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorB_1 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorB_1 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Humidité 1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 36 },
   "targets": [
    {
     "queryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorB_1 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorB_1 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "rawQueryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorB_1 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorB_1 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Température 2",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 41 },
   "targets": [
    {
     "queryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorB_2 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorB_2 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "rawQueryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorB_2 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorB_2 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Humidité 2",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 41 },
   "targets": [
    {
     "queryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorB_2 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorB_2 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "rawQueryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorB_2 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorB_2 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Température 3",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 46 },
   "targets": [
    {
     "queryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorB_3 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorB_3 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "rawQueryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorB_3 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorB_3 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Humidité 3",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 46 },
   "targets": [
    {
     "queryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorB_3 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorB_3 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "rawQueryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorB_3 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorB_3 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Température 4",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 51 },
   "targets": [
    {
     "queryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorB_4 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorB_4 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "rawQueryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorB_4 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorB_4 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Humidité 4",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 51 },
   "targets": [
    {
     "queryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorB_4 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorB_4 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "rawQueryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorB_4 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorB_4 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Mux 3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mux 3",
     "type": "gauge",
     "gridPos": { "h": 20, "w": 6, "x": 0, "y": 117 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT \n    -- Temperature Data\n    CASE WHEN CAST(t.SensorC_1 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorC_1 AS FLOAT) END AS \"Temp 1\",\n    CASE WHEN CAST(h.SensorC_1 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorC_1 AS INTEGER) END AS \"Hum 1\",\n    CASE WHEN CAST(t.SensorC_2 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorC_2 AS FLOAT) END AS \"Temp 2\",\n    CASE WHEN CAST(h.SensorC_2 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorC_2 AS INTEGER) END AS \"Hum 2\",\n    CASE WHEN CAST(t.SensorC_3 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorC_3 AS FLOAT) END AS \"Temp 3\",\n    CASE WHEN CAST(h.SensorC_3 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorC_3 AS INTEGER) END AS \"Hum 3\",\n    CASE WHEN CAST(t.SensorC_4 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorC_4 AS FLOAT) END AS \"Temp 4\",\n    CASE WHEN CAST(h.SensorC_4 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorC_4 AS INTEGER) END AS \"Hum 4\"\nFROM \n    (SELECT * FROM TemperatureData ORDER BY id DESC LIMIT 1) t\nCROSS JOIN \n    (SELECT * FROM HumidityData ORDER BY id DESC LIMIT 1) h;\n",
       "rawQueryText": "SELECT \n    -- Temperature Data\n    CASE WHEN CAST(t.SensorC_1 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorC_1 AS FLOAT) END AS \"Temp 1\",\n    CASE WHEN CAST(h.SensorC_1 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorC_1 AS INTEGER) END AS \"Hum 1\",\n    CASE WHEN CAST(t.SensorC_2 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorC_2 AS FLOAT) END AS \"Temp 2\",\n    CASE WHEN CAST(h.SensorC_2 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorC_2 AS INTEGER) END AS \"Hum 2\",\n    CASE WHEN CAST(t.SensorC_3 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorC_3 AS FLOAT) END AS \"Temp 3\",\n    CASE WHEN CAST(h.SensorC_3 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorC_3 AS INTEGER) END AS \"Hum 3\",\n    CASE WHEN CAST(t.SensorC_4 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorC_4 AS FLOAT) END AS \"Temp 4\",\n    CASE WHEN CAST(h.SensorC_4 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorC_4 AS INTEGER) END AS \"Hum 4\"\nFROM \n    (SELECT * FROM TemperatureData ORDER BY id DESC LIMIT 1) t\nCROSS JOIN \n    (SELECT * FROM HumidityData ORDER BY id DESC LIMIT 1) h;\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Température 1",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 6, "y": 117 },
     "targets": [
      {
       "queryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorC_1 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorC_1 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorC_1 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorC_1 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Humidité 1",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 117 },
     "targets": [
      {
       "queryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorC_1 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorC_1 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorC_1 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorC_1 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Température 2",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 6, "y": 122 },
     "targets": [
      {
       "queryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorC_2 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorC_2 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorC_2 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorC_2 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Humidité 2",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 122 },
     "targets": [
      {
       "queryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorC_2 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorC_2 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorC_2 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorC_2 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Température 3",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 6, "y": 127 },
     "targets": [
      {
       "queryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorC_3 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorC_3 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorC_3 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorC_3 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Humidité 3",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 127 },
     "targets": [
      {
       "queryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorC_3 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorC_3 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorC_3 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorC_3 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Température 4",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 6, "y": 132 },
     "targets": [
      {
       "queryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorC_4 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorC_4 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorC_4 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorC_4 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Humidité 4",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 132 },
     "targets": [
      {
       "queryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorC_4 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorC_4 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorC_4 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorC_4 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Mux 4",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mux 4",
     "type": "gauge",
     "gridPos": { "h": 20, "w": 6, "x": 0, "y": 337 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT \n    -- Temperature Data\n    CASE WHEN CAST(t.SensorD_1 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorD_1 AS FLOAT) END AS \"Temp 1\",\n    CASE WHEN CAST(h.SensorD_1 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorD_1 AS INTEGER) END AS \"Hum 1\",\n    CASE WHEN CAST(t.SensorD_2 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorD_2 AS FLOAT) END AS \"Temp 2\",\n    CASE WHEN CAST(h.SensorD_2 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorD_2 AS INTEGER) END AS \"Hum 2\",\n    CASE WHEN CAST(t.SensorD_3 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorD_3 AS FLOAT) END AS \"Temp 3\",\n    CASE WHEN CAST(h.SensorD_3 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorD_3 AS INTEGER) END AS \"Hum 3\",\n    CASE WHEN CAST(t.SensorD_4 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorD_4 AS FLOAT) END AS \"Temp 4\",\n    CASE WHEN CAST(h.SensorD_4 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorD_4 AS INTEGER) END AS \"Hum 4\"\nFROM \n    (SELECT * FROM TemperatureData ORDER BY id DESC LIMIT 1) t\nCROSS JOIN \n    (SELECT * FROM HumidityData ORDER BY id DESC LIMIT 1) h;\n",
       "rawQueryText": "SELECT \n    -- Temperature Data\n    CASE WHEN CAST(t.SensorD_1 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorD_1 AS FLOAT) END AS \"Temp 1\",\n    CASE WHEN CAST(h.SensorD_1 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorD_1 AS INTEGER) END AS \"Hum 1\",\n    CASE WHEN CAST(t.SensorD_2 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorD_2 AS FLOAT) END AS \"Temp 2\",\n    CASE WHEN CAST(h.SensorD_2 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorD_2 AS INTEGER) END AS \"Hum 2\",\n    CASE WHEN CAST(t.SensorD_3 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorD_3 AS FLOAT) END AS \"Temp 3\",\n    CASE WHEN CAST(h.SensorD_3 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorD_3 AS INTEGER) END AS \"Hum 3\",\n    CASE WHEN CAST(t.SensorD_4 AS FLOAT) = -1 THEN NULL ELSE CAST(t.SensorD_4 AS FLOAT) END AS \"Temp 4\",\n    CASE WHEN CAST(h.SensorD_4 AS INTEGER) = -1 THEN NULL ELSE CAST(h.SensorD_4 AS INTEGER) END AS \"Hum 4\"\nFROM \n    (SELECT * FROM TemperatureData ORDER BY id DESC LIMIT 1) t\nCROSS JOIN \n    (SELECT * FROM HumidityData ORDER BY id DESC LIMIT 1) h;\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Température 1",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 6, "y": 337 },
     "targets": [
      {
       "queryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorD_1 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorD_1 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorD_1 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorD_1 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Humidité 1",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 337 },
     "targets": [
      {
       "queryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorD_1 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorD_1 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorD_1 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorD_1 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Température 2",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 6, "y": 342 },
     "targets": [
      {
       "queryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorD_2 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorD_2 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorD_2 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorD_2 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Humidité 2",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 342 },
     "targets": [
      {
       "queryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorD_2 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorD_2 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorD_2 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorD_2 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Température 3",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 6, "y": 347 },
     "targets": [
      {
       "queryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorD_3 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorD_3 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorD_3 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorD_3 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Humidité 3 ",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 347 },
     "targets": [
      {
       "queryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorD_3 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorD_3 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorD_3 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorD_3 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Température 4",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 6, "y": 352 },
     "targets": [
      {
       "queryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorD_4 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorD_4 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    t.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(t.SensorD_4 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(t.SensorD_4 AS INTEGER) \n    END AS Temp\nFROM TemperatureData t\nORDER BY t.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Humidité 4",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 352 },
     "targets": [
      {
       "queryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorC_4 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorC_4 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "rawQueryText": "SELECT \n    h.timestamp as time,  -- Assuming there's a 'timestamp' or 'time' column in the HumidityData table\n    -- Temperature Data\n    CASE \n        WHEN CAST(h.SensorC_4 AS INTEGER) = -1 THEN NULL \n        ELSE CAST(h.SensorC_4 AS INTEGER) \n    END AS Hum\nFROM HumidityData h\nORDER BY h.timestamp DESC;  -- Assuming 'timestamp' is the column that stores the time of the data\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  }
 ]
}